name: Build in .NET and React

on:
  pull_request:
    branches: ["main"]
    types: [review_requested, reopened, synchronize]

jobs:
  dotnet:
    name: .NET Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  web:
    name: React Build (Web)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: src/web/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: src/web

      - name: Build
        run: npm run build
        working-directory: src/web

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: docker compose build
